# Dockerfile

# Imagen base de la última versión oficial de Python
FROM python:latest

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia archivos del proyecto
COPY . /app

# Instala dependencias si tienes requirements.txt
# RUN pip install -r requirements.txt

# Comando por defecto: abre intérprete de Python
CMD ["python"]
